global:
  domain: localhost
  image:
    tag: v0.1.9
  REDIS_HOST: redis
  REDIS_PORT: 6379
  REDIS_HELPER_HOST: redis-helper
  REDIS_HELPER_PORT: 6379
  REDIS_CHANNEL: TokenStorage_Refresh_Token

# Set this to DEBUG and restart your applications to get more informations in logs. Default: INFO
loglevel: DEBUG
# If you set this to "False", SSL will not be verified in all https requests. Default: "True"
verify_ssl: "True"
proxy:
  http_proxy: "" # empty field
  https_proxy: "" # empty field
  no_proxy: "*"
namespace:
  create: false
  name: "research-data-services"
feature:
  jaeger: false
  redis: true
  nextcloud: false
jaeger:
  ## All jaeger options: https://github.com/jaegertracing/helm-charts
  fullnameOverride: jaeger
  schema:
    activeDeadlineSeconds: 600
redis:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster
  fullnameOverride: redis
  usePassword: false
  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
redis-helper:
  ## All redis-cluster options: https://github.com/bitnami/charts/tree/master/bitnami/redis
  fullnameOverride: redis-helper
  architecture: standalone
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
  replica:
    persistence:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 1Gi
      annotations: {}
  redis:
    config:
      ## All redis options: http://download.redis.io/redis-stable/redis.conf
      min-replicas-to-write: 1
      min-replicas-max-lag: 5
      maxmemory: "0"
      maxmemory-policy: "volatile-lru"
      save: "60 1"
      repl-diskless-sync: "yes"
      rdbcompression: "yes"
      rdbchecksum: "yes"
